apiVersion: v1
kind: ConfigMap
metadata:
   name: sim-configmap

data:
   APP_NAME: Simulator App
   VENDOR: Oracle
   LOG_LEVEL: {{ .Values.global.loglevel}}
   MICROSERVICE_NAME: chf-simulator
   ENGINEERING_VERSION: 1.0
   MYSQL_HOST: {{ .Values.global.mysql.host }}
   MYSQL_PORT: {{ .Values.global.mysql.port | quote }}
   MYSQL_CHF_DB: {{ .Values.global.mysql.chfdbname | quote }}